# Configuração Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:auditoria
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Credenciais AWS
spring.cloud.aws.credentials.access-key=
spring.cloud.aws.credentials.secret-key=
spring.cloud.aws.region.static=us-east-1

# Fila SQS
app.dlq.name=arn:aws:sqs:us-east-1:814369619254:T03_GUSTAVO_BAU_DLQ.fifo

